permalink: /:title/
url: http://yonsm.net
name: Yonsm.NET
author: Yonsm
qq: 123018
email: Yonsm@msn.com
duoshuo: yonsm
beian: 浙ICP备12026616号
cnzz: 119959
weibo: 1885061391
github: Yonsm
pygments: true
safe: true
paginate: 20
about: "这里是 truckli的个人博客，源代码fork自https://github.com/Yonsm/NET"
