markdown: rdiscount
permalink: /:title/
url: http://truckli.github.io
name: Truckli's Blog
author: Truckli
qq: 123018
email: truckli@126.com
duoshuo: None
beian: None
cnzz: 119959
weibo: None
github: truckli 
pygments: true
safe: true
paginate: 20
about: "这里是 truckli的个人博客（从Yonsm.github.com Fork而来）, 正在建设中……"
